import Header from "@/Header";
import Navbar from "@/Navbar";
import Results from "@/Results";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* NavBar */}
      <Navbar />
      {/* Results */}
      <Results />
    </div>
  );
}
